
import java.awt.event.ItemListener;
import java.awt.event.ItemEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JCheckBox;
import java.util.List;
import java.util.ArrayList;
import java.awt.Component;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author aluno
 */
public class VendaPizza extends javax.swing.JFrame {

    int limit = 1;
    List<JCheckBox> checkboxList = new ArrayList<>();
    Component[] components;

    /**
     * Creates new form VendaLanche
     */
    
    public VendaPizza() {
        initComponents();
        components = jPanel4.getComponents();
        for (Component component : components) {
            if (component instanceof JCheckBox) {
                JCheckBox checkBox = (JCheckBox) component;
                checkboxList.add(checkBox);
                checkBox.addItemListener(new ItemListener() {
                    @Override
                    public void itemStateChanged(ItemEvent e) {
                        updateCheckboxState();
                    }
                });
            }
        }
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        bordaCheck = new javax.swing.JCheckBox();
        bordaCheck2 = new javax.swing.JCheckBox();
        bordaCheck3 = new javax.swing.JCheckBox();
        bordaCheck4 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        txf_Total = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_Calcular = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_Sair = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        xSaborCheckBox = new javax.swing.JCheckBox();
        xSaborCheckBox1 = new javax.swing.JCheckBox();
        xSaborCheckBox2 = new javax.swing.JCheckBox();
        xSaborCheckBox3 = new javax.swing.JCheckBox();
        xSaborCheckBox4 = new javax.swing.JCheckBox();
        xSaborCheckBox5 = new javax.swing.JCheckBox();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea14 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea15 = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea16 = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextArea17 = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextArea18 = new javax.swing.JTextArea();
        xSaborCheckBox6 = new javax.swing.JCheckBox();
        xSaborCheckBox7 = new javax.swing.JCheckBox();
        xSaborCheckBox8 = new javax.swing.JCheckBox();
        xSaborCheckBox9 = new javax.swing.JCheckBox();
        xSaborCheckBox10 = new javax.swing.JCheckBox();
        xSaborCheckBox11 = new javax.swing.JCheckBox();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextArea19 = new javax.swing.JTextArea();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTextArea20 = new javax.swing.JTextArea();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextArea21 = new javax.swing.JTextArea();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTextArea22 = new javax.swing.JTextArea();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTextArea23 = new javax.swing.JTextArea();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTextArea24 = new javax.swing.JTextArea();
        xSaborCheckBox12 = new javax.swing.JCheckBox();
        xSaborCheckBox13 = new javax.swing.JCheckBox();
        xSaborCheckBox14 = new javax.swing.JCheckBox();
        xSaborCheckBox15 = new javax.swing.JCheckBox();
        xSaborCheckBox16 = new javax.swing.JCheckBox();
        xSaborCheckBox17 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.black);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bordaCheck.setText("Mussarela com oregano");
        bordaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bordaCheckActionPerformed(evt);
            }
        });

        bordaCheck2.setText("Catupiry");
        bordaCheck2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bordaCheck2ActionPerformed(evt);
            }
        });

        bordaCheck3.setText("Chocolate");
        bordaCheck3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bordaCheck3ActionPerformed(evt);
            }
        });

        bordaCheck4.setText("Cheddar");
        bordaCheck4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bordaCheck4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bordaCheck2)
                    .addComponent(bordaCheck)
                    .addComponent(bordaCheck3)
                    .addComponent(bordaCheck4))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bordaCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bordaCheck2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bordaCheck3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bordaCheck4)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel4.setText("Total ");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_Calcular.setText("Calcular");
        btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_Sair.setText("Sair");
        btn_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(btn_Calcular)
                .addGap(18, 18, 18)
                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_reset)
                    .addComponent(btn_Calcular)
                    .addComponent(btn_Sair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Disk Pizza Leão");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Sabores Doces");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setMaximumSize(new java.awt.Dimension(50, 16));
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 16));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tamanho");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea7.setEditable(false);
        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jTextArea7.setText("Mussarela, leite condensado e paçoca");
        jTextArea7.setBorder(null);
        jScrollPane7.setViewportView(jTextArea7);

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea8.setEditable(false);
        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jTextArea8.setText("Mussarela, leite condensado, \nchocolate branco, morango e creme de\nleite");
        jTextArea8.setBorder(null);
        jScrollPane8.setViewportView(jTextArea8);

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea9.setEditable(false);
        jTextArea9.setColumns(20);
        jTextArea9.setRows(5);
        jTextArea9.setText("Mussarela, leite condensado, \nchocolate preto, morango e creme de\nleite");
        jTextArea9.setBorder(null);
        jScrollPane9.setViewportView(jTextArea9);

        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea10.setEditable(false);
        jTextArea10.setColumns(20);
        jTextArea10.setRows(5);
        jTextArea10.setText("Mussarela, leite condensado, \nchocolate preto e coco");
        jTextArea10.setBorder(null);
        jScrollPane10.setViewportView(jTextArea10);

        jScrollPane11.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea11.setEditable(false);
        jTextArea11.setColumns(20);
        jTextArea11.setRows(5);
        jTextArea11.setText("Mussarela, leite condensado, \nchocolate preto e cerejas");
        jTextArea11.setBorder(null);
        jScrollPane11.setViewportView(jTextArea11);

        jScrollPane12.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane12.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea12.setEditable(false);
        jTextArea12.setColumns(20);
        jTextArea12.setRows(5);
        jTextArea12.setText("Mussarela, leite condensado, \nchocolate branco, granulado colorido");
        jTextArea12.setBorder(null);
        jScrollPane12.setViewportView(jTextArea12);

        xSaborCheckBox.setText("Sedução");
        xSaborCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBoxItemStateChanged(evt);
            }
        });

        xSaborCheckBox1.setText("Paçoquita da neide");
        xSaborCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBox1ItemStateChanged(evt);
            }
        });

        xSaborCheckBox2.setText("Sensação");
        xSaborCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBox2ItemStateChanged(evt);
            }
        });

        xSaborCheckBox3.setText("Prestígio");
        xSaborCheckBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBox3ItemStateChanged(evt);
            }
        });

        xSaborCheckBox4.setText("Floresta Negra");
        xSaborCheckBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBox4ItemStateChanged(evt);
            }
        });

        xSaborCheckBox5.setText("Carnaval");
        xSaborCheckBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBox5ItemStateChanged(evt);
            }
        });

        jScrollPane13.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane13.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea13.setEditable(false);
        jTextArea13.setColumns(20);
        jTextArea13.setRows(5);
        jTextArea13.setText("Molho de tomate especial, mussarela,\nstrogonoff de carne, orégano e batata\npalha");
        jTextArea13.setBorder(null);
        jScrollPane13.setViewportView(jTextArea13);

        jScrollPane14.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane14.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea14.setEditable(false);
        jTextArea14.setColumns(20);
        jTextArea14.setRows(5);
        jTextArea14.setText("Molho de tomate especial, mussarela,\ncalabresa e orégano");
        jTextArea14.setBorder(null);
        jScrollPane14.setViewportView(jTextArea14);

        jScrollPane15.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane15.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea15.setEditable(false);
        jTextArea15.setColumns(20);
        jTextArea15.setRows(5);
        jTextArea15.setText("Molho de tomate especial, mussarela,\nfrango, catupiry e orégano");
        jTextArea15.setBorder(null);
        jScrollPane15.setViewportView(jTextArea15);

        jScrollPane16.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane16.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea16.setEditable(false);
        jTextArea16.setColumns(20);
        jTextArea16.setRows(5);
        jTextArea16.setText("Molho de tomate especial, mussarela,\npresunto, ovo, cebola, tomate, pimentão,\nazeitona e orégano");
        jTextArea16.setBorder(null);
        jScrollPane16.setViewportView(jTextArea16);

        jScrollPane17.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane17.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea17.setEditable(false);
        jTextArea17.setColumns(20);
        jTextArea17.setRows(5);
        jTextArea17.setText("Molho de tomate especial, mussarela,\nfilé mignon, catupiry e orégano");
        jTextArea17.setBorder(null);
        jScrollPane17.setViewportView(jTextArea17);

        jScrollPane18.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane18.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea18.setEditable(false);
        jTextArea18.setColumns(20);
        jTextArea18.setRows(5);
        jTextArea18.setText("Molho de tomate especial, mussarela,\nsalame italiano, tomate, cebola, azeitona\ne orégano");
        jTextArea18.setBorder(null);
        jScrollPane18.setViewportView(jTextArea18);

        xSaborCheckBox6.setText("Calabresa");
        xSaborCheckBox6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBox6ItemStateChanged(evt);
            }
        });

        xSaborCheckBox7.setText("Strogonoff");
        xSaborCheckBox7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBox7ItemStateChanged(evt);
            }
        });

        xSaborCheckBox8.setText("Frango catupiry");
        xSaborCheckBox8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBox8ItemStateChanged(evt);
            }
        });

        xSaborCheckBox9.setText("Portuguesa");
        xSaborCheckBox9.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBox9ItemStateChanged(evt);
            }
        });

        xSaborCheckBox10.setText("Catufilé");
        xSaborCheckBox10.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBox10ItemStateChanged(evt);
            }
        });

        xSaborCheckBox11.setText("Italiana");
        xSaborCheckBox11.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBox11ItemStateChanged(evt);
            }
        });

        jScrollPane19.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane19.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea19.setEditable(false);
        jTextArea19.setColumns(20);
        jTextArea19.setRows(5);
        jTextArea19.setText("Molho de tomate especial, mussarela,\ncamarão ao molho, champignon, milho,\nazeitona e orégano");
        jTextArea19.setBorder(null);
        jScrollPane19.setViewportView(jTextArea19);

        jScrollPane20.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane20.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea20.setEditable(false);
        jTextArea20.setColumns(20);
        jTextArea20.setRows(5);
        jTextArea20.setText("Molho de tomate especial, mussarela,\nfilezinho da picanha, cebola, azeitona,\n catupiry, bacon em fatias e orégano");
        jTextArea20.setBorder(null);
        jScrollPane20.setViewportView(jTextArea20);

        jScrollPane21.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane21.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea21.setEditable(false);
        jTextArea21.setColumns(20);
        jTextArea21.setRows(5);
        jTextArea21.setText("Molho de tomate especial, mussarela,\nlinguiça assada, pimenta, calabresa, \ncebola, pimentão azeitona e orégano");
        jTextArea21.setBorder(null);
        jScrollPane21.setViewportView(jTextArea21);

        jScrollPane22.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane22.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea22.setEditable(false);
        jTextArea22.setColumns(20);
        jTextArea22.setRows(5);
        jTextArea22.setText("Molho de tomate especial, mussarela,\nfatias de ponta de peito, champignon, \ntomate em fatias e orégano");
        jTextArea22.setBorder(null);
        jScrollPane22.setViewportView(jTextArea22);

        jScrollPane23.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane23.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea23.setEditable(false);
        jTextArea23.setColumns(20);
        jTextArea23.setRows(5);
        jTextArea23.setText("Molho de tomate especial, mussarela e\nquatro ingredientes a preferência do \ncliente");
        jTextArea23.setBorder(null);
        jScrollPane23.setViewportView(jTextArea23);

        jScrollPane24.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane24.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea24.setEditable(false);
        jTextArea24.setColumns(20);
        jTextArea24.setRows(5);
        jTextArea24.setText("Molho de tomate especial, mussarela,\nfilezinho de picanha ao alho e cebola");
        jTextArea24.setBorder(null);
        jScrollPane24.setViewportView(jTextArea24);

        xSaborCheckBox12.setText("A moda da casa");
        xSaborCheckBox12.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBox12ItemStateChanged(evt);
            }
        });

        xSaborCheckBox13.setText("Camarão");
        xSaborCheckBox13.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBox13ItemStateChanged(evt);
            }
        });

        xSaborCheckBox14.setText("Baiana do beto");
        xSaborCheckBox14.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBox14ItemStateChanged(evt);
            }
        });

        xSaborCheckBox15.setText("Ponta de Peito");
        xSaborCheckBox15.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBox15ItemStateChanged(evt);
            }
        });

        xSaborCheckBox16.setText("Sabor do Cliente");
        xSaborCheckBox16.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBox16ItemStateChanged(evt);
            }
        });

        xSaborCheckBox17.setText("Tudo de bom");
        xSaborCheckBox17.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                xSaborCheckBox17ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xSaborCheckBox)
                            .addComponent(xSaborCheckBox2)
                            .addComponent(xSaborCheckBox4)
                            .addComponent(xSaborCheckBox5)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(xSaborCheckBox3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(xSaborCheckBox1)))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xSaborCheckBox6)
                            .addComponent(xSaborCheckBox8)
                            .addComponent(xSaborCheckBox10)
                            .addComponent(xSaborCheckBox11)
                            .addComponent(xSaborCheckBox9)
                            .addComponent(xSaborCheckBox7)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xSaborCheckBox12)
                            .addComponent(xSaborCheckBox14)
                            .addComponent(xSaborCheckBox16)
                            .addComponent(xSaborCheckBox17)
                            .addComponent(xSaborCheckBox15)
                            .addComponent(xSaborCheckBox13)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(xSaborCheckBox12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xSaborCheckBox14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xSaborCheckBox15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xSaborCheckBox13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xSaborCheckBox16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xSaborCheckBox17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(xSaborCheckBox6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(xSaborCheckBox8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(xSaborCheckBox9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xSaborCheckBox7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(xSaborCheckBox10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xSaborCheckBox11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(xSaborCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(xSaborCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(xSaborCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xSaborCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(xSaborCheckBox4)
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xSaborCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Sabores Tradicionais");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setMaximumSize(new java.awt.Dimension(50, 16));
        jLabel6.setMinimumSize(new java.awt.Dimension(50, 16));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Bordas");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Sabores Especiais");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setMaximumSize(new java.awt.Dimension(50, 16));
        jLabel8.setMinimumSize(new java.awt.Dimension(50, 16));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequena: 1 sabor, 8 fatias e 25cm R$ 20,00", "Média: 2 sabores, 12 fatias R$ 37,00", "Grande: 3 sabores, 16 fatias R$ 47,00", "Grande familia: 4 sabores, 20 fatias R$ 67,00", "Big: 4 sabores, 24 fatias R$ 82,00", "Big retangular: 4 sabores, 32 fatias R$ 77,00" }));
        jComboBox1.setSelectedItem(-1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(542, 542, 542)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(132, 132, 132))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(112, 112, 112)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txf_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void updateCheckboxState() {
        int selectedCount = 0;

        for (JCheckBox checkbox : checkboxList) {
            if (checkbox.isSelected()) {
                selectedCount++;
            }
        }

        for (JCheckBox checkbox : checkboxList) {
            if (!checkbox.isSelected() && selectedCount >= limit) {
                checkbox.setEnabled(false);
            } else {
                checkbox.setEnabled(true);
            }
        }
    }
    private void btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularActionPerformed
        double total = 0;

        switch (jComboBox1.getSelectedIndex()) {
            case 0:
                total = total + 20.00;
                break;
            case 1:
                total = total + 37.00;
                break;
            case 2:
                total = total + 47.00;
                break;
            case 3:
                total = total + 67.00;
                break;
            case 4:
                total = total + 82.00;
                break;
            case 5:
                total = total + 77.00;
                break;
        }

        txf_Total.setText(Double.toString(total));


    }//GEN-LAST:event_btn_CalcularActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        bordaCheck.setSelected(false);
        bordaCheck3.setSelected(false);
        bordaCheck2.setSelected(false);
        txf_Total.setText("");
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_SairActionPerformed

    private void bordaCheck2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bordaCheck2ActionPerformed
        if(bordaCheck2.isSelected()){
            bordaCheck4.setSelected(false);
            bordaCheck3.setSelected(false);
            bordaCheck.setSelected(false);
        }
    }//GEN-LAST:event_bordaCheck2ActionPerformed

    private void bordaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bordaCheckActionPerformed
        if(bordaCheck.isSelected()){
            bordaCheck4.setSelected(false);
            bordaCheck3.setSelected(false);
            bordaCheck2.setSelected(false);
        }
    }//GEN-LAST:event_bordaCheckActionPerformed

    private void bordaCheck4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bordaCheck4ActionPerformed
       if(bordaCheck4.isSelected()){
            bordaCheck.setSelected(false);
            bordaCheck3.setSelected(false);
            bordaCheck2.setSelected(false);
        }
    }//GEN-LAST:event_bordaCheck4ActionPerformed

    private void xSaborCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBoxItemStateChanged
        xSaborCheckBox.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateCheckboxState();
            }
        });
    }//GEN-LAST:event_xSaborCheckBoxItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        switch (jComboBox1.getSelectedIndex()) {
            case 0:
                limit = 1;
                break;
            case 1:
                limit = 2;
                break;
            case 2:
                limit = 3;
                break;
            case 3:
                limit = 4;
                break;
            case 4:
                limit = 4;
                break;
            case 5:
                limit = 4;
                break;
        }
        if (jComboBox1.getSelectedIndex() != -1) {
            for (int i = 0; i < checkboxList.size(); i++) {
                checkboxList.get(i).setEnabled(true);
            }
            // Adicione mais linhas para habilitar as demais checkboxes
        } else {
            for (int i = 0; i < checkboxList.size(); i++) {
                checkboxList.get(i).setEnabled(false);
            }
            // Adicione mais linhas para desabilitar as demais checkboxes
        }
        txf_Total.setText(String.valueOf(limit));
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void xSaborCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBox2ItemStateChanged
        xSaborCheckBox2.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateCheckboxState();
            }
        });
    }//GEN-LAST:event_xSaborCheckBox2ItemStateChanged

    private void xSaborCheckBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBox3ItemStateChanged
        xSaborCheckBox3.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateCheckboxState();
            }
        });
    }//GEN-LAST:event_xSaborCheckBox3ItemStateChanged

    private void xSaborCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBox1ItemStateChanged
        xSaborCheckBox1.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                int numSelected = 0; // Inicializa o número de checkboxes selecionadas como zero

                for (JCheckBox checkBox : checkboxList) {
                    if (checkBox.isSelected()) {
                        numSelected++; // Incrementa o número de checkboxes selecionadas
                    }
                }
                
                // se o número máximo de checkboxes for atingido, desative todas as checkboxes
                if (numSelected >= limit) {
                    // Desativa todas as checkboxes não selecionadas
                    for (JCheckBox checkBox : checkboxList) {
                        if (!checkBox.isSelected()) {
                            checkBox.setEnabled(false);
                        }
                    }
                } else {
                    // Habilita todas as checkboxes
                    for (JCheckBox checkBox : checkboxList) {
                        checkBox.setEnabled(true);
                    }
                }

            }
        });
    }//GEN-LAST:event_xSaborCheckBox1ItemStateChanged

    private void xSaborCheckBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBox4ItemStateChanged
        xSaborCheckBox4.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateCheckboxState();
            }
        });
    }//GEN-LAST:event_xSaborCheckBox4ItemStateChanged

    private void xSaborCheckBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBox5ItemStateChanged
        xSaborCheckBox5.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateCheckboxState();
            }
        });
    }//GEN-LAST:event_xSaborCheckBox5ItemStateChanged

    private void xSaborCheckBox6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBox6ItemStateChanged
        xSaborCheckBox6.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateCheckboxState();
            }
        });
    }//GEN-LAST:event_xSaborCheckBox6ItemStateChanged

    private void xSaborCheckBox8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBox8ItemStateChanged
        xSaborCheckBox8.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateCheckboxState();
            }
        });
    }//GEN-LAST:event_xSaborCheckBox8ItemStateChanged

    private void xSaborCheckBox9ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBox9ItemStateChanged
        xSaborCheckBox9.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateCheckboxState();
            }
        });
    }//GEN-LAST:event_xSaborCheckBox9ItemStateChanged

    private void xSaborCheckBox7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBox7ItemStateChanged
        xSaborCheckBox7.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateCheckboxState();
            }
        });
    }//GEN-LAST:event_xSaborCheckBox7ItemStateChanged

    private void xSaborCheckBox10ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBox10ItemStateChanged
        xSaborCheckBox10.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateCheckboxState();
            }
        });
    }//GEN-LAST:event_xSaborCheckBox10ItemStateChanged

    private void xSaborCheckBox11ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBox11ItemStateChanged
        xSaborCheckBox11.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateCheckboxState();
            }
        });
    }//GEN-LAST:event_xSaborCheckBox11ItemStateChanged

    private void xSaborCheckBox12ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBox12ItemStateChanged
        xSaborCheckBox12.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateCheckboxState();
            }
        });
    }//GEN-LAST:event_xSaborCheckBox12ItemStateChanged

    private void xSaborCheckBox14ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBox14ItemStateChanged
        xSaborCheckBox14.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateCheckboxState();
            }
        });
    }//GEN-LAST:event_xSaborCheckBox14ItemStateChanged

    private void xSaborCheckBox15ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBox15ItemStateChanged
        xSaborCheckBox15.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateCheckboxState();
            }
        });
    }//GEN-LAST:event_xSaborCheckBox15ItemStateChanged

    private void xSaborCheckBox13ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBox13ItemStateChanged
        xSaborCheckBox13.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateCheckboxState();
            }
        });
    }//GEN-LAST:event_xSaborCheckBox13ItemStateChanged

    private void xSaborCheckBox16ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBox16ItemStateChanged
        xSaborCheckBox16.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateCheckboxState();
            }
        });
    }//GEN-LAST:event_xSaborCheckBox16ItemStateChanged

    private void xSaborCheckBox17ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_xSaborCheckBox17ItemStateChanged
        xSaborCheckBox17.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                updateCheckboxState();
            }
        });
    }//GEN-LAST:event_xSaborCheckBox17ItemStateChanged

    private void bordaCheck3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bordaCheck3ActionPerformed
        if(bordaCheck3.isSelected()){
            bordaCheck4.setSelected(false);
            bordaCheck.setSelected(false);
            bordaCheck2.setSelected(false);
        }
    }//GEN-LAST:event_bordaCheck3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaPizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bordaCheck;
    private javax.swing.JCheckBox bordaCheck2;
    private javax.swing.JCheckBox bordaCheck3;
    private javax.swing.JCheckBox bordaCheck4;
    private javax.swing.JButton btn_Calcular;
    private javax.swing.JButton btn_Sair;
    private javax.swing.JButton btn_reset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea15;
    private javax.swing.JTextArea jTextArea16;
    private javax.swing.JTextArea jTextArea17;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea19;
    private javax.swing.JTextArea jTextArea20;
    private javax.swing.JTextArea jTextArea21;
    private javax.swing.JTextArea jTextArea22;
    private javax.swing.JTextArea jTextArea23;
    private javax.swing.JTextArea jTextArea24;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JTextField txf_Total;
    private javax.swing.JCheckBox xSaborCheckBox;
    private javax.swing.JCheckBox xSaborCheckBox1;
    private javax.swing.JCheckBox xSaborCheckBox10;
    private javax.swing.JCheckBox xSaborCheckBox11;
    private javax.swing.JCheckBox xSaborCheckBox12;
    private javax.swing.JCheckBox xSaborCheckBox13;
    private javax.swing.JCheckBox xSaborCheckBox14;
    private javax.swing.JCheckBox xSaborCheckBox15;
    private javax.swing.JCheckBox xSaborCheckBox16;
    private javax.swing.JCheckBox xSaborCheckBox17;
    private javax.swing.JCheckBox xSaborCheckBox2;
    private javax.swing.JCheckBox xSaborCheckBox3;
    private javax.swing.JCheckBox xSaborCheckBox4;
    private javax.swing.JCheckBox xSaborCheckBox5;
    private javax.swing.JCheckBox xSaborCheckBox6;
    private javax.swing.JCheckBox xSaborCheckBox7;
    private javax.swing.JCheckBox xSaborCheckBox8;
    private javax.swing.JCheckBox xSaborCheckBox9;
    // End of variables declaration//GEN-END:variables
}
