/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import dao.PizzaDAO;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Cliente;
import models.Pedido;
import models.Pizza;

/**
 *
 * @author hawks
 */
public class AdicionarPedido extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarPedido
     */
    int limit = 1;
    String tamanho = "";
    private final Cliente cliente;
    
    List<Pedido> listaDePedido = new ArrayList<>();
    List<Pizza> listaDeSabores = new ArrayList<>();
    List<Pizza> saboresSelecionados = new ArrayList<>();
    PizzaDAO pizzaDAO = new PizzaDAO();
    public AdicionarPedido(Cliente cliente, List<Pedido> listaDePedido) {
        this.cliente = cliente;
        this.listaDePedido = listaDePedido;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tamanhoComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPizzaVenda = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        bordaCheddar = new javax.swing.JRadioButton();
        bordaMussarela = new javax.swing.JRadioButton();
        bordaChocolate = new javax.swing.JRadioButton();
        bordaCatupiry = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        adicionarSabor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaSaboresSelecionados = new javax.swing.JTable();
        removerSabor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jButtonDoces1 = new javax.swing.JRadioButton();
        jButtonDoces = new javax.swing.JRadioButton();
        adicionarPizza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Tamanho");

        tamanhoComboBox.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        tamanhoComboBox.setForeground(new java.awt.Color(255, 102, 0));
        tamanhoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequena: 1 sabor, 8 fatias e 25cm R$ 20,00", "Média: 2 sabores, 12 fatias R$ 37,00", "Grande: 3 sabores, 16 fatias R$ 47,00", "Grande familia: 4 sabores, 20 fatias R$ 67,00", "Big: 4 sabores, 24 fatias R$ 82,00", "Big retangular: 4 sabores, 32 fatias R$ 77,00" }));
        tamanhoComboBox.setSelectedItem(-1);
        tamanhoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanhoComboBoxActionPerformed(evt);
            }
        });

        tabelaPizzaVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(tabelaPizzaVenda);

        jPanel2.setBackground(new java.awt.Color(90, 90, 90));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        buttonGroup1.add(bordaCheddar);
        bordaCheddar.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        bordaCheddar.setForeground(new java.awt.Color(255, 102, 0));
        bordaCheddar.setText("Cheddar");

        buttonGroup1.add(bordaMussarela);
        bordaMussarela.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        bordaMussarela.setForeground(new java.awt.Color(255, 102, 0));
        bordaMussarela.setText("Mussarela com oregano");

        buttonGroup1.add(bordaChocolate);
        bordaChocolate.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        bordaChocolate.setForeground(new java.awt.Color(255, 102, 0));
        bordaChocolate.setText("Chocolate");

        buttonGroup1.add(bordaCatupiry);
        bordaCatupiry.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        bordaCatupiry.setForeground(new java.awt.Color(255, 102, 0));
        bordaCatupiry.setText("Catupiry");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bordaCheddar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bordaChocolate)
                .addGap(18, 18, 18)
                .addComponent(bordaMussarela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bordaCatupiry)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bordaCheddar)
                    .addComponent(bordaChocolate)
                    .addComponent(bordaMussarela)
                    .addComponent(bordaCatupiry))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("Borda");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pizza3.png"))); // NOI18N

        adicionarSabor.setText("Adicionar");
        adicionarSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarSaborActionPerformed(evt);
            }
        });

        tabelaSaboresSelecionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Sabores Selecionado"
            }
        ));
        jScrollPane2.setViewportView(tabelaSaboresSelecionados);

        removerSabor.setText("Remover");
        removerSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerSaborActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 119, 26));
        jLabel6.setText("Filtrar sabores por:");

        jRadioButton5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 119, 26));
        jRadioButton5.setText("~Sabores Especiais~");

        jButtonDoces1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonDoces1.setForeground(new java.awt.Color(255, 119, 26));
        jButtonDoces1.setText("~Sabores Tradicionais~");

        jButtonDoces.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonDoces.setForeground(new java.awt.Color(255, 119, 26));
        jButtonDoces.setText("~Sabores Doces~");
        jButtonDoces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDocesActionPerformed(evt);
            }
        });

        adicionarPizza.setText("Finalizar");
        adicionarPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarPizzaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonDoces)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDoces1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(removerSabor)
                                .addGap(18, 18, 18)
                                .addComponent(adicionarPizza)
                                .addGap(0, 32, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(98, 98, 98))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tamanhoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addContainerGap(121, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adicionarSabor)
                .addGap(337, 337, 337))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tamanhoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDoces)
                            .addComponent(jButtonDoces1)
                            .addComponent(jRadioButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removerSabor)
                            .addComponent(adicionarPizza))))
                .addGap(28, 28, 28)
                .addComponent(adicionarSabor)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tamanhoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanhoComboBoxActionPerformed
        switch (tamanhoComboBox.getSelectedIndex()) {
            case 0:
                limit = 1;
                break;
            case 1:
                limit = 2;
                break;
            case 2:
                limit = 3;
                break;
            case 3:
                limit = 4;
                break;
            case 4:
                limit = 4;
                break;
            case 5:
                limit = 4;
                break;
        }
    }//GEN-LAST:event_tamanhoComboBoxActionPerformed
    private void atualizarTabelaPizza() {
        try {
            listaDeSabores = pizzaDAO.buscarListaDePizzas();
            DefaultTableModel model = (DefaultTableModel) tabelaPizzaVenda.getModel();
            model.setNumRows(0);
            for (int i = 0; i < listaDeSabores.size(); i++) {
                Pizza pizza = listaDeSabores.get(i);
                String nomePizza = pizza.getNome();
                String ingredientes = pizza.getIngredientes();
                String tipo = pizza.getTipo();

                model.addRow(new Object[]{nomePizza, ingredientes, tipo});
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    private String retornaBorda(){
        if(bordaCheddar.isSelected()){
            return "Cheddar";
        }
        else if(bordaMussarela.isSelected()){
            return "Chocolate";
        }
        else if(bordaChocolate.isSelected()){
            return "Mussarela com oregano";
        }else if(bordaCatupiry.isSelected()){
            return "Catupiry";
        }
        return "Sem borda";
    }
    private void jButtonDocesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDocesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDocesActionPerformed
    
    private void adicionarSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarSaborActionPerformed
        int linha =tabelaPizzaVenda.getSelectedRow();
        if(linha<0){
            JOptionPane.showMessageDialog(null, "Selecione um sabor para adicionar","Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Pizza pizzaSelecionado = listaDeSabores.get(linha); 
        saboresSelecionados.add(pizzaSelecionado);
        atualizarTabelaSelecionados();
    }//GEN-LAST:event_adicionarSaborActionPerformed

    private void removerSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerSaborActionPerformed
        int linha =tabelaSaboresSelecionados.getSelectedRow();
        if(linha<0){
            JOptionPane.showMessageDialog(null, "Selecione um endereço","Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Pizza saborRemovido = saboresSelecionados.remove(linha);
        atualizarTabelaSelecionados();
    }//GEN-LAST:event_removerSaborActionPerformed
     private BigDecimal calcularValorTotal(){
        boolean isBordaCheck = false;
        double total = 0;
        if(bordaCheddar.isSelected() || bordaMussarela.isSelected() || bordaChocolate.isSelected() || bordaCatupiry.isSelected()){
            isBordaCheck = true;
        }
        switch (tamanhoComboBox.getSelectedIndex()) {
            case 0:
                tamanho = "PEQUENA";
                if(isBordaCheck){
                    total += 23.00;
                }else{
                    total += 20.00;
                }
                break;
            case 1:
                tamanho = "MÉDIA";
                if(isBordaCheck){
                    total += 43.00;
                }else{
                    total += 37.00;
                }
                break;
            case 2:
                tamanho = "GRANDE";
                if(isBordaCheck){
                    total += 54.00;
                }else{
                    total += 47.00;
                }
                break;
            case 3:
                tamanho = "GRANDE FAMILIA";
                if(isBordaCheck){
                    total += 74.00;
                }else{
                    total += 67.00;
                }
                break;
            case 4:
                tamanho = "BIG";
                if(isBordaCheck){
                    total += 92.00;
                }else{
                    total += 82.00;
                }
                break;
            case 5:
                tamanho = "BIG RETANGULAR";
                if(isBordaCheck){
                    total += 87.00;
                }else{
                    total += 77.00;
                }
                break;
        }
        
        return new BigDecimal(total);
    }
    private void adicionarPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPizzaActionPerformed
        BigDecimal total = calcularValorTotal();
        listaDePedido.add(new Pedido(tamanho, saboresSelecionados, retornaBorda(), total));
        VendaPizza pizza = new VendaPizza(cliente, listaDePedido);
        pizza.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adicionarPizzaActionPerformed

    /**
     * @param args the command line arguments
     */
    private void atualizarTabelaSelecionados() {
        DefaultTableModel model = (DefaultTableModel) tabelaSaboresSelecionados.getModel();
        model.setNumRows(0);
        for (int i = 0; i < saboresSelecionados.size(); i++) {
            Pizza pizza = saboresSelecionados.get(i);
            String nomePizza = pizza.getNome();
            String ingredientes = pizza.getIngredientes();
            String tipo = pizza.getTipo();
            model.addRow(new Object[]{nomePizza, ingredientes, tipo});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarPizza;
    private javax.swing.JButton adicionarSabor;
    private javax.swing.JRadioButton bordaCatupiry;
    private javax.swing.JRadioButton bordaCheddar;
    private javax.swing.JRadioButton bordaChocolate;
    private javax.swing.JRadioButton bordaMussarela;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jButtonDoces;
    private javax.swing.JRadioButton jButtonDoces1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removerSabor;
    private javax.swing.JTable tabelaPizzaVenda;
    private javax.swing.JTable tabelaSaboresSelecionados;
    private javax.swing.JComboBox<String> tamanhoComboBox;
    // End of variables declaration//GEN-END:variables
}
