package views;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author igora
 */
import api.Request;
import java.awt.Color;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import models.Endereco;
import models.Pedido;
import models.NotaFiscal;
import models.User;
public class DadosDoCliente extends javax.swing.JFrame {
    /**
     * Creates new form DadosDoCliente
     */
    private final User user;
    private final List<Pedido> pedidos;
    private final Request request;
    private List<Endereco> enderecos;
    
    public DadosDoCliente(User user, List<Pedido> pedidos) {
        this.user = user;
        this.pedidos = pedidos;
        request = new Request();
        initComponents();
        getContentPane().setBackground(Color.DARK_GRAY);
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tCEP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tDescricao = new javax.swing.JTextField();
        jDescricaoCadastro = new javax.swing.JLabel();
        tBairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tNumero = new javax.swing.JTextField();
        jNumero = new javax.swing.JLabel();
        btn_FecharPedido = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        tDescricaoBuscaPedido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_finalizar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(90, 90, 90));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        tCEP.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("CEP");

        tDescricao.setToolTipText("");

        jDescricaoCadastro.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        jDescricaoCadastro.setForeground(new java.awt.Color(255, 102, 0));
        jDescricaoCadastro.setText("Descrição");

        tBairro.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("Bairro");

        tNumero.setToolTipText("");

        jNumero.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        jNumero.setForeground(new java.awt.Color(255, 102, 0));
        jNumero.setText("Numero");

        btn_FecharPedido.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        btn_FecharPedido.setForeground(new java.awt.Color(255, 102, 0));
        btn_FecharPedido.setText("Cadastrar");
        btn_FecharPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FecharPedidoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("Novo endereço");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(214, 214, 214)
                .addComponent(jLabel5)
                .addGap(115, 115, 115))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jNumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jDescricaoCadastro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btn_FecharPedido)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDescricaoCadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btn_FecharPedido)
                .addGap(24, 24, 24))
        );

        jLabel9.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("Selecione um endereço para entrega");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo (1).png"))); // NOI18N

        tabela1.setBackground(new java.awt.Color(90, 90, 90));
        tabela1.setForeground(new java.awt.Color(255, 255, 255));
        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DESCRIÇÃO", "CEP", "BAIRRO", "NUMERO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tabela1);

        tDescricaoBuscaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDescricaoBuscaPedidoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("Descrição");

        jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Buscar");

        btn_finalizar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btn_finalizar.setForeground(new java.awt.Color(255, 102, 0));
        btn_finalizar.setText("Finalizar pedido");
        btn_finalizar.setToolTipText("Para selecionar um endereço você precisa clicar em um");
        btn_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tDescricaoBuscaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel9)))))
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(btn_finalizar)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tDescricaoBuscaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_finalizar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tDescricaoBuscaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDescricaoBuscaPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDescricaoBuscaPedidoActionPerformed

    private void btn_FecharPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FecharPedidoActionPerformed
       /*
         String diretorio = "C:\\pedidos";
        String saboresConc = "";
        String bebidasConc = "";
        File diretorioArquivos = new File(diretorio);
        if (!diretorioArquivos.exists()) {
            // Se o diretório não existe, crie-o
            diretorioArquivos.mkdirs();
        }
        File[] files = diretorioArquivos.listFiles();
        if(sabores.size() == 1){
            saboresConc = sabores.get(0);
        }else{
            for(int i = 0; i < sabores.size(); i++){
                if(i + 1 < sabores.size()){
                    saboresConc += sabores.get(i) + "/";
                }else{
                    saboresConc += sabores.get(i);
                }
            }
        }
        if(bebidas.size() == 1){
            bebidasConc = bebidas.get(0).toString();
        }else{
            for(int i = 0; i < bebidas.size(); i++){
                if(i + 1 < bebidas.size()){
                    bebidasConc += bebidas.get(i).toString() + "/";
                }else{
                    bebidasConc += bebidas.get(i).toString();
                }
            }
        }
        data = new Date();
        int ultimoPedido = 0;
        for (File file : files) {
            if (file.getName().startsWith("pedido")) {
                String[] parts = file.getName().split("pedido");
                int numeroPedido = Integer.parseInt(parts[1].substring(0, parts[1].indexOf(".")));
                if (numeroPedido > ultimoPedido) {
                    ultimoPedido = numeroPedido;
                }
            }
        }
        ultimoPedido++;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String dataFormatada = formato.format(data);
        String layout = "-------------------------------------------------\n";
        layout += "         NOTA FISCAL DISK PIZZA LEÃO         \n";
        layout += "-------------------------------------------------\n";
        layout += String.format("Nº Pedido: %d    Data: %s\n", ultimoPedido, dataFormatada);
        layout += "-------------------------------------------------\n";
        layout += String.format("Cliente: %s\n", tName.getText());
        layout += String.format("Endereço: %s, %s - %s\nComplemento: %s\n", tDescricao.getText(), tNumero.getText(), tBairro.getText(), tNumero.getText());
        layout += "-------------------------------------------------\n";
        layout += "               ITENS DO PEDIDO               \n";
        layout += String.format("Pizza tamanho: %s\nSabores: %s\nBorda: %s\n", tamanho, saboresConc ,borda);
        layout += String.format("Bebidas: %s\n", bebidasConc);
        layout += "-------------------------------------------------\n";
        layout += String.format("Total: R$ %6.2f\n", total);
        try{
            File arquivo = new File(diretorio,"pedido" + ultimoPedido +".txt");
            FileWriter escritor = new FileWriter(arquivo);
            escritor.write(layout);
            escritor.close();
            JOptionPane.showMessageDialog(this, "Pedido gerado com sucesso!", "Pedido", JOptionPane.INFORMATION_MESSAGE);

        }
        catch(IOException ex){
            JOptionPane.showMessageDialog(this, "Erro ao gerar pedido:" + ex.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        */
    }//GEN-LAST:event_btn_FecharPedidoActionPerformed

    private void btn_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizarActionPerformed
        int linha =tabela1.getSelectedRow();
        BigDecimal valorTotal = calculaValorTotalDoPedido();
        if(linha<0){
            JOptionPane.showMessageDialog(null, "Selecione um endereco","Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            NotaFiscal nf = new NotaFiscal(user.getId(), retornaIdEndereco(linha), valorTotal);
            request.inserirNotaFiscal(nf, pedidos);
            JOptionPane.showMessageDialog(null, "Pedido Gerado com sucesso!");        
            // Fechar o formulário atual
            this.dispose();
        } catch (SQLException ex) {
            ex.printStackTrace();
             JOptionPane.showMessageDialog(null, "Erro ao inserir no bd","Erro", JOptionPane.ERROR_MESSAGE);   
        }
    }//GEN-LAST:event_btn_finalizarActionPerformed
    private void atualizarTabela() { 
        try {
            enderecos = request.buscarPelaDescricao(tDescricaoBuscaPedido.getText(), user.getId());

            DefaultTableModel model = (DefaultTableModel) tabela1.getModel();
            model.setNumRows(0);
            for (int i = 0; i < enderecos.size(); i++) {
                Endereco pessoa = enderecos.get(i);
                model.addRow(new Object[]{pessoa.getRua(), pessoa.getCep(), pessoa.getBairro(), pessoa.getNumero(),});
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }       
    }
    private int retornaIdEndereco(int linha){
        Endereco enderecoSelecionado = enderecos.get(linha);
        return enderecoSelecionado.getCodigo();
    }
    private BigDecimal calculaValorTotalDoPedido(){
        BigDecimal valorTotal = BigDecimal.ZERO;
        for(Pedido pedido:pedidos){
            valorTotal.add(pedido.getValorTotal());
        }
        return valorTotal;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_FecharPedido;
    private javax.swing.JButton btn_finalizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jDescricaoCadastro;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jNumero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tBairro;
    private javax.swing.JTextField tCEP;
    private javax.swing.JTextField tDescricao;
    private javax.swing.JTextField tDescricaoBuscaPedido;
    private javax.swing.JTextField tNumero;
    private javax.swing.JTable tabela1;
    // End of variables declaration//GEN-END:variables
}
